include logstash-config-integration-testing/Makefile

# .PHONY: install-deps
# install-deps::
#     # Not really needed.
#     # /usr/share/logstash/bin/logstash-plugin install logstash-filter-environment
#     $(LOGSTASH_PLUGIN) install logstash-filter-cidr
